# Author: Hung Vu

version: "3.8"

services:
  caddy:
    container_name: caddy
    restart: always
    image: "ghcr.io/hunghvu/blogfolio-caddy:main"
    networks:
      - blogfolio
    environment:
      - CADDY_INGRESS_NETWORKS=blogfolio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3 support https://caddyserver.com/docs/running#docker-compose
    labels:
      caddy.acme_dns: cloudflare REDACTED

  web:
    container_name: web
    restart: always
    image: "ghcr.io/hunghvu/blogfolio-web:main"
    networks:
      - blogfolio
    ports:
      - "127.0.0.1:3000:3000"
    deploy:
      resources:
        limits:
          memory: 300M
    labels:
      caddy: hungvu.tech
      caddy.tls.resolvers: 1.1.1.1 1.0.0.1
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.encode: zstd gzip

  cms:
    container_name: cms
    restart: always
    env_file: ./.env.production.local
    image: "ghcr.io/hunghvu/blogfolio-cms:main"
    networks:
      - blogfolio
    ports:
      - "127.0.0.1:3100:3100"
    deploy:
      resources:
        limits:
          memory: 300M
    labels:
      caddy: payload.hungvu.tech
      caddy.tls.resolvers: 1.1.1.1 1.0.0.1
      caddy.reverse_proxy: "{{upstreams 3100}}"
      caddy.encode: zstd gzip

networks:
  # Network name cannot be "default"
  # And the network must be external, or else caddy cannot connect to other containers
  # Error: "container not in the same network as caddy" via "docker logs --follow caddy"
  blogfolio:
    driver: bridge
    external: true

volumes:
  caddy_data:
